channels:
- conda-forge
dependencies:
- python=3.10.14
- pip<=23.3.1
- pip:
  - mlflow==2.12.1
  - catboost==1.2.5
  - colorama==0.4.6
  - ipython==8.23.0
  - numpy==1.26.4
  - pandas==2.2.2
  - scipy==1.13.0
name: mlflow-env
